services:
  - type: web
    name: epi-recognition-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: PORT
        value: 5001
